[package]
name = "zsh-sys"
version = "0.1.0"
edition = "2021"
description = "Low-level bindings to zsh internals"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = '0.69.2'
